### ISSUE TITLE
QR Code

### ISSUE THREAD

**Issue by Thibis** [BinaryWorlds/ThermalPrinter#1]
Hi, how are you?

Is it possible to print a QR Code with this code?

I can generate the pixels of QR with (x,y) and the colour of it (black or white).

Thanks for all

**Comment by BinaryWorlds** [comment]
Hi!
The library currently doesn't support bitmap / barcode printing.
Unfortunately, I don't have time to add this functionality.

I've done quick research for you.
You can test yourself by implementing a solution for yourself.

You can print the QR code as a bar code.
The printer supports many barcode systems (page 44) 
[pdf]( https://cdn-shop.adafruit.com/datasheets/CSN-A2+User+Manual.pdf)
First you need to generate the valid QR code (you can use online generator).
Then convert it to a string(u can use Windows LCD Assistant tool).

U need to write function/method like this(its only a sketch):
In TPrinter.h
```
#define GS 29 

//in public:
void printBarCode(char *text, uint8_t barCodeSystem);
```

In TPrinter.cpp:

```
void Tprinter::printBarCode(char *text, uint8_t barCodeSystem){ // barCodeSystem 0-10
  
  wait();

  stream->write(GS);
  stream->write('k');
  stream->write(barCodeSystem);

  int textLength = strlen(text);
  if(textLength > 255) textLength = 255;

  stream->write(textLength);
  for(uint8_t i = 0; i < textLength; i++){
    wait();
    stream->write(text[i]);//or try next line(not sure it work well):
    //write(text[i]);
  }
  // use this function after enabling this mode:  myPrinter.enableDtr(pinNR);
  // if not, u should use here(and in for loop) setDelay(val);
}

```

It's only example - not tested.
Propably it's need more configuration(like set dot height, width and printing left space).

Good luck!

**Comment by BinaryWorlds** [comment]
Hi!
This library currently doesn't support bitmap / barcode printing.
Unfortunately, I don't have time to add this functionality.
