### ISSUE TITLE
Font sizes

### ISSUE THREAD

**Issue by jenshackel** [BinaryWorlds/ThermalPrinter#2]
I have an issue to change from a larger font - use of. setMode(FONT_B, DOUBLE_WIDTH, DOUBLE_HEIGHT);
back to a smaller font. I found nocthing (so far) in the documentation. Can you probably give an example how to switch back to reguar font_b ?

**Comment by BinaryWorlds** [comment]
Hi.
check out the examples.

List of modes, definied in [TPrinter.h](../blob/master/TPrinter.h) :

```
#define FONT_B 1              // Font B: 9x17, Standard font A: 12x24
#define DARK_MODE (1 << 1)    // anti-white mode, didn't work?
#define UPSIDE_DOWN (1 << 2)  // didn't work?, use invert(bool);
#define BOLD (1 << 3)
#define DOUBLE_HEIGHT (1 << 4)
#define DOUBLE_WIDTH (1 << 5)
#define STRIKEOUT (1 << 6)  // didn't work?
```

We set each option using a function:
```
myPrinter.setMode();
```

and unset with:

```
myPrinter.unsetMode();
```
You can **pass up to 7** arguments to the function(mix like in example).


**Unset in your case:**

```
myPrinter.unsetMode(DOUBLE_WIDTH, DOUBLE_HEIGHT);
```

Or after begin(), just set:
```
myPrinter.setMode(FONT_B);
```

**Comment by jenshackel** [comment]
Awesome! Thanks for your fast support. That helped. Now my project is running :-)
kindest regards & go on with this great lib !!!

**Comment by BinaryWorlds** [comment]
I'm glad I could help!
