### ISSUE TITLE
use bigger font size with the library

### ISSUE THREAD

**Issue by khadeja829** [BinaryWorlds/ThermalPrinter#3]
Hi, Thank you for the great library, The library worked fine but I have a small issue, I want to use bigger font size than the implemented font A and font B. I use double height and double width but the font  still smaller than what I need. Could you please guide me how to implement bigger font size into library and how to call the new font into my Arduino sketch.(I need font B and very much bigger font(s)).Thank you very much for your help.

**Comment by BinaryWorlds** [comment]
Based on this documentation:
[https://ebc81.files.wordpress.com/2014/08/701print-driver-board.pdf](https://ebc81.files.wordpress.com/2014/08/701print-driver-board.pdf)
(page 10), you can implement a user-defined character set.

In that case, you should not use the autoCalculate() function. Instead, utilize the DTR pin or experimentally adjust the timing using setTimes().

In my opinion, it might be faster and easier for you to generate letters as bitmaps and print them at any scale. This is a functionality you need to implement on your own.

Good luck!
