### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Bobbik1** [BinaryWorlds/ThermalPrinter#4]
Could it be add posibility to use with serial bluetooth and BT printer?

**Comment by BinaryWorlds** [comment]
This library is dedicated to thermal printers from a specific series (qr701, adafruit) that utilize the Serial port. This means that it has been designed for communication with a specific firmware that communicates in a very precise manner.

Handling a Bluetooth printer involves:

Adding Bluetooth protocol support.
Handling a specific family of printers and their way of communicating with the firmware.
You haven't specified which printer you need the software for, but you should be able to find a dedicated library within your own scope.

It's also worth considering the chosen solution during the design stage. For example, I used this library to communicate with the printer, but I sent the print content via Wi-Fi from another MCU, following this approach:

MCU 1 <-- Wi-Fi --> MCU 2 <-- Serial port --> Qr701 printer

However, this is a solution that you need to implement on your own.

Good luck!

**Comment by BinaryWorlds** [comment]
This library is dedicated to thermal printers from a specific series (qr701, adafruit) that utilize the Serial port. This means that it has been designed for communication with a specific firmware that communicates in a very precise manner.

Handling a Bluetooth printer involves:
- Adding Bluetooth protocol support.
- Handling a specific family of printers and their way of communicating with the firmware.

You haven't specified which printer you need the software for, but nevertheless, you should find a dedicated library on your own.

It's also worth considering the chosen solution during the design stage. For example, I used this library to communicate with the printer, but I sent the print content via Wi-Fi from another MCU, following this approach:

MCU 1 <-- Wi-Fi --> MCU 2 <-- Serial port --> Qr701 printer

However, this is a solution that you need to implement on your own.

Good luck!
