### ISSUE TITLE
Not Exactly!!

### ISSUE THREAD

**Issue by The3ven** [BinaryWorlds/ThermalPrinter#5]
Printer model: e.g A1X-URL
Printer firmware: e.g 2.0
Library release: e.g v1.0

i just want to know how you make bitmap for your library link qr code 
any tool or esp library you used to make bitmap,
sorry to open this i didn't find any contact link to you so this is the only way i`m found to contact with you!

**Comment by BinaryWorlds** [comment]
To generate QR codes from a microprocessor, you can use the following library:
https://github.com/ricmoo/QRCode
