### ISSUE TITLE
Doesnt't work with Arduino Nano ESP32

### ISSUE THREAD

**Issue by emmess0000** [BinaryWorlds/ThermalPrinter#6]
Printer model: JP-QR701
Printer firmware: QR701-N32-2009
Library relase: latest

**Describe the bug**
Unable to get it running on a Arduino Nano ESP32.

**To Reproduce**
first_view_esp32.ino

**Expected behavior**
Print something :-)

**Additional context**
The printer doesn't do anything. In my opinion everything is correct wired (RX to RXpin, TX to TXpin), played around with DTR LOW&HIGH, changed the Baudrate, but the printer is still silent :-D

**Comment by BinaryWorlds** [comment]
In my opinion, you are doing something wrong. 😄  There is too little information for me to help you. I suggest that you read the comments in the code and examples.

https://github.com/BinaryWorlds/ThermalPrinter/blob/master/examples/first_view_esp32/first_view_esp32.ino

Have fun!
