### ISSUE TITLE
[BUG] Garbage being printed instead of bitmap

### ISSUE THREAD

**Issue by LucasTor** [BinaryWorlds/ThermalPrinter#8]
Printer model: QR701
Printer firmware: ? e.g 2.69
Library relase: e.g v1.0

**Describe the bug**

The printer prints a lot of garbage characters instead of the expected bitmap, this happens even in the examples

**To Reproduce**
Paste simple code(.ino) making bug - not your whole project.

**Expected behavior**

**Screenshots**

![image](https://github.com/BinaryWorlds/ThermalPrinter/assets/25714552/7afd3fcb-dc57-4edd-97d8-71a710590a60)

**Additional context**

**Comment by BinaryWorlds** [comment]
It's not a software error but a data transmission issue. You have poor quality, unshielded cables. Use max3485 communication modules on a PCB. I recommend using an oscilloscope.

**Comment by bluewingtitan** [comment]
> It's not a software error but a data transmission issue.

Are you sure about this? I got the same issue and the "garbage" characters being printed are identical between runs. There is no noise that could come from interference. (Using your QR-Code example)

![Image](https://github.com/user-attachments/assets/860c13a4-f056-47e6-9821-9ba516afd0ab)
